### ISSUE TITLE
Where is the website for this shared task?

### ISSUE THREAD

**Issue by seq2struct** [GoThereGit/EvaHan#2]
Where is the website for this shared task?

**Comment by cble99** [comment]
The website is [https://github.com/GoThereGit/EvaHan](https://github.com/GoThereGit/EvaHan).

**Comment by seq2struct** [comment]
I'd like to know the website link for task registration.

**Comment by cble99** [comment]
If you would like to register the task, please send a request email to evahan2025@gmail.com. We will then provide you with the registration file to complete.
